version: '2'

services:
   db1:
     image: mysql:8
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: jbdee
       MYSQL_USER: root
       MYSQL_PASSWORD: root
     ports:
       - "3306:3306"

   db2:
     image: mysql:8
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: jbdee_rest
       MYSQL_USER: root
       MYSQL_PASSWORD: root
     ports:
       - "3307:3306"